services:
  db:
    image: postgres:15-alpine
    container_name: viruscan_db
    restart: always
    environment:
      POSTGRES_USER: viruscan_user
      POSTGRES_PASSWORD: viruscan_pass_2024
      POSTGRES_DB: viruscan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U viruscan_user -d viruscan_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - viruscan_network

  backend:
    build: .
    container_name: viruscan_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://viruscan_user:viruscan_pass_2024@db:5432/viruscan_db
      FLASK_APP: app.py
      FLASK_ENV: production
      SECRET_KEY: x2n05X5JJfAKVklF3pC0CpJUHNT3UqYK
      POSTGRES_USER: viruscan_user
      POSTGRES_PASSWORD: viruscan_pass_2024
      POSTGRES_DB: viruscan_db
     
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - viruscan_network

  adminer:
    image: adminer:latest
    container_name: viruscan_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - viruscan_network

volumes:
  postgres_data:

networks:
  viruscan_network:
    driver: bridge
